[phases.setup]
cmds = [
    "mkdir -p storage/framework/cache",
    "mkdir -p storage/framework/sessions",
    "mkdir -p storage/framework/views",
    "mkdir -p storage/logs",
    "mkdir -p bootstrap/cache"
]